hyperskill_project:
  id: 220
  ide_files: https://stepik.org/media/attachments/lesson/621544/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Mon, 05 Sep 2022 07:34:43 UTC
stages:
- id: 1101
  step: 17036
  is_completed: true
- id: 1102
  step: 17037
  is_completed: true
- id: 1103
  step: 17038
  is_completed: true
- id: 1104
  step: 17039
  is_completed: true
- id: 1105
  step: 17040
  is_completed: true
- id: 1106
  step: 17041
  is_completed: true
